-- Création de la table YEARBOOK_Group
CREATE TABLE YEARBOOK_Group (
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(30) UNIQUE NOT NULL,
	CONSTRAINT pk_JEE_Group_idG PRIMARY KEY (id)
) ENGINE=INNODB, AUTO_INCREMENT = 1;

-- Création de la table YEARBOOK_Person
CREATE TABLE YEARBOOK_Person (
	id BIGINT NOT NULL AUTO_INCREMENT,
	lastName VARCHAR(20) NOT NULL,
	firstName VARCHAR (20) NOT NULL,
	email VARCHAR (30) UNIQUE NOT NULL,
	homePage VARCHAR(30) UNIQUE,
	birthDate DATE NOT NULL,
	pwd VARCHAR(70) NOT NULL,
	idG BIGINT,
	CONSTRAINT pk_YEARBOOK_Person_idP PRIMARY KEY (id),
	CONSTRAINT fk_YEARBOOK_Person_idG_YEARBOOK_Group FOREIGN KEY (idG)
		REFERENCES YEARBOOK_Group (id)
		ON DELETE SET NULL
		ON UPDATE CASCADE
) ENGINE=INNODB, AUTO_INCREMENT = 1;