-- Création de la table JEE_Group
CREATE TABLE JEE_Group (
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(30) UNIQUE NOT NULL,
	CONSTRAINT pk_JEE_Group_idG PRIMARY KEY (id)
);

-- Création de la table JEE_Person
CREATE TABLE JEE_Person (
	id BIGINT NOT NULL AUTO_INCREMENT,
	lastName VARCHAR(20) NOT NULL,
	firstName VARCHAR (20) NOT NULL,
	email VARCHAR (30) UNIQUE NOT NULL,
	homePage VARCHAR(30) UNIQUE,
	birthDate DATE NOT NULL,
	pwd VARCHAR(70) NOT NULL,
	idG BIGINT,
	CONSTRAINT pk_JEE_Person_idP PRIMARY KEY (id),
	CONSTRAINT fk_JEE_Person_idG_JEE_Group FOREIGN KEY (idG)
		REFERENCES JEE_Group (id)
		ON DELETE SET NULL
		ON UPDATE CASCADE
);