-- Données de test insertion de groupes dans la base

INSERT INTO YEARBOOK_Group (name) VALUES ('M2_FED');
INSERT INTO YEARBOOK_Group (name) VALUES ('M2_RO');
INSERT INTO YEARBOOK_Group (name) VALUES ('M2_IF');
INSERT INTO YEARBOOK_Group (name) VALUES ('M2_RIM');
INSERT INTO YEARBOOK_Group (name) VALUES ('M2_SIS');
INSERT INTO YEARBOOK_Group (name) VALUES ('M2_ISL');
INSERT INTO YEARBOOK_Group (name) VALUES ('M2_FSI');
INSERT INTO YEARBOOK_Group (name) VALUES ('M2_GL');
INSERT INTO YEARBOOK_Group (name) VALUES ('M2_SIR');